### ISSUE TITLE
How to do integration test in a multi-project setup

### ISSUE THREAD

**Issue by fowlie** [akhikhl/gretty#102]
Hi,

We have a multi-project gradle build with 20 submodules. Each submodule has its own farm, and each farm shares a lot of common modules. So the ***farmIntegrationTest*** task seems very inefficient, as it would start and stop the common modules many times. 

Is it possible to call ***farmStartWar***, run all integration tests and then finally call ***farmStopWar***?

Thanks!

**Comment by akhikhl** [comment]
Hi Mats,
Does Gretty 1.1.8 solve the issue for you?
Can we close this issue?

**Comment by fowlie** [comment]
Hi! I guess we can close this now. Although we decided to do things slightly different and did not need this feature any more. That being said, I was voting for this feature though :smiley:
