### ISSUE TITLE
how to use extraResourceBase

### ISSUE THREAD

**Issue by anjingxz** [akhikhl/gretty#117]
gretty {
	port = 9999
	servletContainer = 'tomcat7'
	managedClassReload = true
	extraResourceBase 'skin/default'
}

I use <appStart> command to start my web app, but the static files in  'skin/default' was not found

**Comment by akhikhl** [comment]
What is the error message in the browser?
Do you see anything interesting in gretty log?

**Comment by akhikhl** [comment]
I close the issue, assuming you resolved it all on your own.
