### ISSUE TITLE
Integration tests in separate project

### ISSUE THREAD

**Issue by strindberg** [akhikhl/gretty#122]
We have a project structure where we have a web application in sub project ":web" and then a separate project for integration tests called ":intTest". I can't find a way to use gretty's support for integration tests to work for this setup. 

What I want to do is the following:
1) Start a web server with the ":web" application.
2) Run tests in ":intTest:intTests"
3) Stop the web server.

I have tried the following in ":intTest":

    farm {
        webapp ':web'
        integrationTestTask = 'intTests'
    }

    task intTests(type: Test, dependsOn: build) {
        ...
    }

When I run "gradle farmIntegrationTest" the web application is started, but the task ":intTest:intTests"is never run, only ":web:intTests". It seems this is in line with the documentation that the mentioned task is run for every web application project, and the ":intTest" project is not a web application.

However, for us it makes sense to have the integration tests in a separate project. Is there a way to achieve this with gretty?

**Comment by akhikhl** [comment]
@strindberg, I've made improvements in farm configuration and startup in Gretty 1.1.9-SNAPSHOT. Please feel free to test it.
Gretty release 1.1.9 is due on 03.03.2015.
