### ISSUE TITLE
tomcat initParameter not working

### ISSUE THREAD

**Issue by gaborbernat** [akhikhl/gretty#126]
Hello, 

initParameter (http://akhikhl.github.io/gretty-doc/Gretty-configuration.html) works only if the container is jetty, 

Somehow it's not passed to the tomcat container. 

Thanks,

**Comment by akhikhl** [comment]
Which gradle task you use?

**Comment by akhikhl** [comment]
I confirm, there's a bug: init-parameter does not get passed from gretty configuration to tomcat 7/8. I'll have a look...

**Comment by gaborbernat** [comment]
Cool +1, thanks,
