### ISSUE TITLE
Filter onScanFilesChanged

### ISSUE THREAD

**Issue by aegliv** [akhikhl/gretty#131]
Hi Andrey,

thank you for putting your time into this wonderful tool. 

In our deployment scenario, we have a `webapp.properties` file in `src/main/resources` which contains the default configuration for our Spring managed Java application. However, for local development deployments, it is desirable to change some values form time to time. Since these changes are meaningful to one machine only, they should not be version controlled. Hence, I want to be able to override the file locally.

I wrote a closure attached to _gretty onStart_ which overrides the properties file in `build/resources/main/` to archive this. This works great as long as _fastReload_ is not enabled. But with _fastReload_ enabled my closure is no longer called and the properties file is overridden once again, but now with the original values.

I tried to attach the closure to _onScanFilesChanged_ as well, but then I end up in an infinite loop, since my changes trigger a rescan!

Is there a way to filter the list of changed Files, so I could *exclude* the `webapp.properties` file from triggering a reload?

Or is there an even better way to achieve the same effect?

Thanks,
Aegliv

**Comment by aegliv** [comment]
Ok, 

since neither _onStart_ nor _onScanFilesChanged_ helped in my case, I eventually solved my use case by hooking up to the `processResources` task:

    ...
    apply plugin: 'org.akhikhl.gretty'
    
    processResources.outputs.upToDateWhen { false } // disable update check
    processResources << {
        for (name in project.gradle.startParameter.taskNames) {
            if (name.contains("jetty") || name.contains("Inplace")) {
                def myFile = new File("build/resources/main/my.properties")
                def fileText = myFile.text
                def map = [
                    /my.property/ : "value",
                    /other.property/ : 60
                ]

               for (String field in map.keySet()) {
                   def replaceWith = map.get(field)
                   fileText = fileText.replaceAll(field + '=(.*)', field + '=' + replaceWith)
               }
               break
            }
        }
    }

**Comment by akhikhl** [comment]
Hi @aegliv,
Sorry for delay with an answer, I was busy with other things.

processResources seems to be the right place for resource modification.

I can suggest another solution:

```groovy
// build.gradle
import org.apache.tools.ant.filters.*
processResources {
  def props = [
    /my.property/ : "value",
    /other.property/ : 60
  ]
  inputs.properties props
  filter ReplaceTokens, tokens: props
}
```
You can use @my.property@ patterns in the resource files, they will be replaced to corresponding values.
