### ISSUE TITLE
Inheriting logging options to generated product fails

### ISSUE THREAD

**Issue by ttheuer** [akhikhl/gretty#152]
I have set `logDir` and `logFileName` in my build.gradle for the gretty plugin, and when I run it with `gradle appRun` it puts the logs where I want.

When I run `gradle buildProduct` and run that with `run.sh` it puts the logs in the default locations.  
Other options, e.g. `contextPath` inherit correctly.

**Comment by akhikhl** [comment]
gretty 1.2.1-SNAPSHOT solves this problem. Now logDir and logFileName are correctly passed to the product.
Release 1.2.1 is coming soon.

**Comment by akhikhl** [comment]
Gretty 1.2.1 is released. Please switch to it and try using logDir and logFileName again.

**Comment by akhikhl** [comment]
Did you have a chance to test it on 1.2.1?

**Comment by ttheuer** [comment]
To be honest, I'm not quite up to speed with the logging aspect of the project right now.
It seems to work, but I got to put some work into it to figure out if everything works like I want it to ;)

**Comment by akhikhl** [comment]
I'm glad to hear that, thank you :smile:
