### ISSUE TITLE
Enable JSR 356

### ISSUE THREAD

**Issue by gaborbernat** [akhikhl/gretty#155]
When developing a websocket at start I get: 

```
Not running on Jetty, JSR-356 support unavailable
```

Adding a jetty-env.xml of:

```xml
<?xml version="1.0"?>
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
    <Call name="setAttribute">
        <Arg>org.eclipse.jetty.websocket.jsr356</Arg>
        <Arg type="Boolean">true</Arg>
    </Call>
</Configure>
```
I get the error:

```
java.lang.IllegalArgumentException: Object of class 'org.akhikhl.gretty.JettyWebAppContext' is not of type 'org.eclipse.jetty.webapp.WebAppContext'. Object Class and type Class are from different loaders.
```

**Comment by akhikhl** [comment]
Can you provide an example to reproduce the problem?

**Comment by akhikhl** [comment]
Please format XML snippets with triple backticks, as described [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code).

**Comment by gaborbernat** [comment]
Updated :)

**Comment by akhikhl** [comment]
Can you provide a self-contained example program? Do you use spring-boot?

**Comment by gaborbernat** [comment]
No sping bot, but I'll try to create an example tomorrow.

**Comment by akhikhl** [comment]
gretty 1.2.1-SNAPSHOT brings out-of-the-box support of websocket and two new examples showing how to use websocket:

https://github.com/akhikhl/gretty/tree/master/examples/websocket

https://github.com/akhikhl/gretty/tree/master/examples/springBootWebSocket

Release 1.2.1 will contain all this.

**Comment by gaborbernat** [comment]
I can confirm that my project too works with 1.2.1.
