### ISSUE TITLE
gretty.baseURI returns 0.0.0.0:8080 instead of localhost:8080 for Jetty9 server

### ISSUE THREAD

**Issue by jseminck** [akhikhl/gretty#160]
Hello,

I'm writing some IntegrationTests and I noticed that the gretty.baseURI variable changed from returning http://localhost:8080 when using tomcat7 to http://0.0.0.0:8080 when using jetty9. 

Using open("/") correctly returns http://localhost:8080/

Not sure if this is intended? Or a bug? Or related to configuration on my side? I couldn't find any similar topics on this problem, hence this post.

Thanks,
Joachim

**Comment by akhikhl** [comment]
I'll have a look at the problem.

**Comment by akhikhl** [comment]
I confirm, it is localhost under tomcat7 and 0.0.0.0 under jetty9. Looking further...

**Comment by akhikhl** [comment]
Fixed in Gretty 1.2.1-SNAPSHOT.
Release 1.2.1 is coming soon.

**Comment by akhikhl** [comment]
Gretty release 1.2.1 is out, please test.

**Comment by jseminck** [comment]
Hello,

This is not working correctly. Thanks for the quick response.

Thanks,
Joachim

**Comment by akhikhl** [comment]
Not working correctly? Could you, please, give more details?

**Comment by jseminck** [comment]
Woops, sorry! Monday morning... :) 
Edited response: it IS working correctly.

**Comment by akhikhl** [comment]
I'm happy to hear that :+1:
