### ISSUE TITLE
1.2.1 and 1.2.2 use default DEBUG level logger of logback in built product

### ISSUE THREAD

**Issue by zhanghuabin** [akhikhl/gretty#164]
Env: Spring Boot 1.2.3 + Gretty + A logback.groovy in my project

Steps:
1. Run buildProduct (Tomcat8 or Jetty9).
2. Run ./start.sh in $buildDir/output/$projectName/start.sh

Expected:
That logback.groovy in my project should be used.

Actual:
That default ROOT logger with DEBUG level defined in LoggerContext constructor is always applied even if I remove the folder starter/logback-config.

Thanks

**Comment by akhikhl** [comment]
Could you, please, provide example project to reproduce a problem?

**Comment by akhikhl** [comment]
Fixed with release 1.2.3, please test
