### ISSUE TITLE
Scan and compile dependencies automatically

### ISSUE THREAD

**Issue by levsa** [akhikhl/gretty#170]
Is there a way already to scan dependent projects (compile dependencies) and compile them automatically for hot deploy? Right now I can see that manually compiling a dependency triggers hot deploy (jar updated), and adding a scanDir detects a change but doesn't recompile.

I found the "scanDependencies" flag in the code but not in the documentation. Although it doesn't seem to trigger recompile either.

I'd be glad to help implementing this feature since it would be very useful.

**Comment by akhikhl** [comment]
This was resolved with https://github.com/akhikhl/gretty/commit/c9d37ceefaf30167fda81c6881c292e6141d8288, thanks to @saladinkzn .
The solution will be released with Gretty 1.4.0.
