### ISSUE TITLE
webappCopy doesn't seem to setup inputs/outputs

### ISSUE THREAD

**Issue by levsa** [akhikhl/gretty#173]
I have some copying from src/test/resources into the webapp directory in the webappCopy section in gretty configuration, but it doesn't seem to rerun the copying when the source files change. It would be nice if it worked the same way as the rest of the gradle copy tasks, so that we don't have to clean/rerun when rebuilding.

Specifically, I've changed src/test/resources/WEB-INF/web.xml and I have the following:

```gradle
gretty {
    webappCopy {
        from "$projectDir/src/test/resources"
        include "**/*"
    }
   ...
}
```
But when running gradlew, I get:

> ./gradlew prepareInplaceWebAppFolder
:iwa:iwa-integration-test:prepareInplaceWebAppFolder UP-TO-DATE

**Comment by akhikhl** [comment]
I fixed the problem in Gretty 1.2.4-SNAPSHOT. Now webappCopy defines inputs and outputs of prepareInplaceWebAppFolder task.
Could you, please, test it?

**Comment by levsa** [comment]
I couldn't test the snapshot, getting this error:

```
      > Could not resolve org.akhikhl.gretty:gretty:1.2.4-SNAPSHOT.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/org/akhikhl/gretty/gretty/1.2.4-SNAPSHOT/maven-metadata.xml.
            > Could not GET 'https://jcenter.bintray.com/org/akhikhl/gretty/gretty/1.2.4-SNAPSHOT/maven-metadata.xml'.
               > peer not authenticated
```

**Comment by levsa** [comment]
I see that 1.2.4 is released, tested and it works ok. About the error above: changed to http for jcenter and it worked better. Thanks for the fix!
