### ISSUE TITLE
Doesn't Work On Debug Mode

### ISSUE THREAD

**Issue by leeyoungalias** [akhikhl/gretty#176]
Gradle 2.4(2.3 also).

this is Terminal output

#####Run:Gradle appStartDebug

	:compileJava UP-TO-DATE
	:processResources UP-TO-DATE
	:classes UP-TO-DATE
	:prepareInplaceWebAppClasses UP-TO-DATE
	:prepareInplaceWebAppFolder UP-TO-DATE
	:prepareInplaceWebApp UP-TO-DATE
	:appStartDebug
	Listening for transport dt_socket at address: 5005

No Exception.
But projet didn't run and debugger(IDEA) can't connection 
and webpage can't visit.

#####Run:gradle appRun

	:compileJava UP-TO-DATE
	:processResources UP-TO-DATE
	:classes UP-TO-DATE
	:prepareInplaceWebAppClasses UP-TO-DATE
	:prepareInplaceWebAppFolder UP-TO-DATE
	:prepareInplaceWebApp UP-TO-DATE
	:appRun
	16:33:55 INFO Tomcat 8.0.22 started and listening on port 80
	16:33:55 INFO test runs at:
	16:33:55 INFO http://localhost:80/test
	Press any key to stop the server.
    Building 85% > :appRun

build.gradle File:

	apply plugin: "war"
	apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'
	apply plugin: "idea"
	
	sourceCompatibility = 1.8
	version = '1.0'

	repositories {
	mavenCentral()
	maven {
	url "https://maven.java.net/content/repositories/releases/"
	}
	}

	dependencies {
	compile 'javax.servlet:javax.servlet-api:3.1.0'
	compile 'org.hibernate:hibernate-core:4.3.10.Final'
	compile 'org.postgresql:postgresql:9.4-1201-jdbc41'
	compile 'com.alibaba:fastjson:1.2.5'
	compile 'com.sun.mail:all:1.5.3'
	compile 'javax.mail:javax.mail-api:1.5.3'
	compile 'javax.mail:mail:1.4.7'
	runtime 'javax.servlet:jstl:1.2'
	testCompile 'org.testng:testng:6.8.17'
	}

	test {
		useTestNG()
	}

	gretty {
		port = 80
		contextPath = "/test"
		servletContainer = 'tomcat8'
	}

**Comment by leeyoungalias** [comment]
Gradle 2.3 Don't work too.

**Comment by akhikhl** [comment]
Sorry, I don't understand the description of the problem. Could you, please:

1. Use markdown triple backtick (```) for code formatting
2. Describe the expected behavior of the program
3. Describe the actual behavior of the program
4. Ask concretely, what should be fixed

**Comment by leeyoungalias** [comment]
update,Sorry for my English.

**Comment by akhikhl** [comment]
Please set debugger port to the value specified in IntelliJ IDEA preferences, as described in the documentation: http://akhikhl.github.io/gretty-doc/Debugger-support.html
