### ISSUE TITLE
Cannot add a configuration with name 'versionManagement'

### ISSUE THREAD

**Issue by fowlie** [akhikhl/gretty#177]
Hi,

I've been playing around with Spring Boot, but once I apply the gretty plugin and the spring-boot plugin I get this error message:
```java
> Failed to apply plugin [id 'spring-boot']
   > Cannot add a configuration with name 'versionManagement' as a configuration with that name already exists.
```
Is there a work around for this?

Regards,
Mats

**Comment by akhikhl** [comment]
Which version of spring-boot?
Can you provide a simple project allowing to reproduce an error?
I'm asking because Gretty contains plenty of spring-boot examples, all of them compile and run without errors.

**Comment by fowlie** [comment]
Ah, now I get it. With Gretty you enable spring-boot with
```groovy
gretty {
    springBoot = true
}
```
and not like this
```groovy
apply plugin: 'spring-boot'
```
I didn't read the documentation good enough. Thanks! :smile:

**Comment by akhikhl** [comment]
I'm happy to hear that you solved the problem :smile:
