### ISSUE TITLE
Unable to use log4j-slf4j-impl

### ISSUE THREAD

**Issue by martinraie** [akhikhl/gretty#182]
Hi,

We're trying to use log4j-slf4j-impl for logging but something adds slf4j-nop also to classpath and in some cases logging doesn't work at all. I suspect the problem is in https://github.com/akhikhl/gretty/blob/master/libs/gretty/src/main/groovy/org/akhikhl/gretty/GrettyPlugin.groovy#L142 which doesn't consider log4j-slf4j-impl slf4j implementation. Could you please add this exception also?

**Comment by akhikhl** [comment]
I added log4j-slf4j-impl to the recognized slf4j implementations.
The change is already effective on snapshot version 1.2.4-SNAPSHOT. Could you, please, test it?

**Comment by akhikhl** [comment]
Please use jfrog's snapshot repository, as described here: http://akhikhl.github.io/gretty-doc/Getting-started.html

**Comment by martinraie** [comment]
Thanks for the quick fix. Now it works as expected. When will the final (non snapshot) version be released?

**Comment by akhikhl** [comment]
Release 1.2.4 is to be expected on Monday, 1 of July, 2015.

**Comment by akhikhl** [comment]
Fixed in Gretty 1.2.4, please test.
