### ISSUE TITLE
No warning when port service is already in use

### ISSUE THREAD

**Issue by escardin** [akhikhl/gretty#185]
I hit an issue recently where the default service port was already in use when doing gradle appRun, gradle would just stall waiting for a response that never comes, because the app listening on port 9000 wasn't expecting such a request. Could you add a check that the service ports are not in use before starting the app with those ports and fail or fallback somehow if they are?

**Comment by akhikhl** [comment]
OK, I'll see to that

**Comment by akhikhl** [comment]
Fixed in Gretty 1.2.4, please test.

**Comment by escardin** [comment]
Works great! Thanks!
