### ISSUE TITLE
Debugging not working in Gretty

### ISSUE THREAD

**Issue by gurminder-sti** [akhikhl/gretty#186]
I am trying to start the application in debug mode using tasks like appStartDebug, tomcatStartWarDebug etc.
the console shows last statement as Listening for transport dt_socket at address: 5005.
After that it does not show anything.
However the appStart and tomcatStart works well.

**Comment by akhikhl** [comment]
It's in the suspended mode. When your IDE connects over that port, you'll have to click "resume" to actually resume the debugged process.

You can disable suspended mode and have it running as usual, with the configuration property:

```groovy
gretty {
  debugSuspend = false
}
```

Please have a look at the documentation: http://akhikhl.github.io/gretty-doc/Debugger-support.html

**Comment by gurminder-sti** [comment]
Thanks a ton for the help,
It worked..
