### ISSUE TITLE
Possibility to run multiple gretty builds on different ports

### ISSUE THREAD

**Issue by levsa** [akhikhl/gretty#195]
Is it possible to run multiple gretty builds on different ports simultaneously? I've tried running different gradle builds with different settings for httpPort in gretty configuration but I get the error "> Web-server is already running."

The reason I want to do this is to run a jetty in one process for manual browsing while running integration tests in another process. It would be ok if integration tests could run with the already running  gretty server. I.e. if there was an option to tell gretty to not exist if server is already running, but just continue the integration test.

**Comment by akhikhl** [comment]
Can you provide an example of (simplified) build.gradle? So that I can use the one for simulating the problem.

**Comment by levsa** [comment]
I just tested the helloGretty example in the repo with this modification to build.gradle:

```gradle
gretty {
    ...
    httpPort = project.hasProperty("httpPort") ? project.httpPort as int : 8080
}
```
Then:
* Run tests on another port: `gradle integrationTest -PhttpPort=8085`
 * You can see that tests are run against a server on port 8085
* start a server in another shell using default port (8080): `gradle jettyRun`
* Run tests again on another port: `gradle integrationTest -PhttpPort=8085`
 * Web-server is already running error.

**Comment by akhikhl** [comment]
@saladinkzn provided the solution for this in Gretty 1.2.6. I am going to deliver Gretty 1.4.0, that will contain this solution as well.

**Comment by xtuer** [comment]
Updated to gretty 1.4.0 and the issue still exists, it prompts Web-server is already running.
