### ISSUE TITLE
java.lang.Exception: Timeout scanning annotations

### ISSUE THREAD

**Issue by mmoayyed** [akhikhl/gretty#222]
I continually run into this problem with the `jetty9` configuration. Tried `-Dorg.eclipse.jetty.annotations.maxWait=9000` :) and that still did not fix the problem. 

`-Dorg.eclipse.jetty.annotations.maxWait=120` worked perfectly fine with the maven jetty plugin, though that was pulling in jetty 9.3. 

Suggestions?

**Comment by tuxbear** [comment]
Hola!

I had the same issue, and this might be a case of not passing system properties to the JVM that jetty runs in. If I remember correctly, gretty (gradle) and jetty, does not run in the same JVM.

For gretty to put system properties into the JVM that Jetty runs in, you must pass it through in the gradle config section of gretty:

gretty {
...
    jvmArgs = ['-Djava.net.preferIPv4Stack=true']

    if (System.properties['org.eclipse.jetty.annotations.maxWait'] != null) {
        jvmArgs.add('-Dorg.eclipse.jetty.annotations.maxWait=' + System.properties['org.eclipse.jetty.annotations.maxWait'])
    }
}

check out: http://akhikhl.github.io/gretty-doc/Gretty-configuration.html

**Comment by mmoayyed** [comment]
Yup. That's what I ended up doing as well. Thanks for the tip.

**Comment by matthew-b-payne** [comment]
Curious, how does one configure Gretty to have jetty not scan at all?

**Comment by istolga** [comment]
+1 the same issue
Ubuntu 14 gradle 2.14 https is on
What strange it doesn't happen on aws servers with the same configuration, only on physical.
Entropy is fine - around 3000

**Comment by abishekk** [comment]
I'd like to solve this by not having to scan as well. It makes little sense to wait for 2+ minutes when developing

**Comment by abishekk** [comment]
Fixed it with 

gretty {
    webInfIncludeJarPattern = ''
}
