### ISSUE TITLE
Support for NeedClientAuth?

### ISSUE THREAD

**Issue by jmrossy** [akhikhl/gretty#224]
Are there any plans to expose the NeedClientAuth ssl config through gretty? 

    <Configure id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory">
          <Set name="KeyStorePath"><Property name="jetty.base" default="." />/<Property name="jetty.keystore" default="etc/keystore"/></Set>
          [...]
          <Set name="NeedClientAuth">true</Set>

Is there any workaround to set it now?

Thank you!

**Comment by shollander** [comment]
+1

Without this functionality gretty is useless to me.

**Comment by akhikhl** [comment]
Resolved with https://github.com/akhikhl/gretty/commit/9bbad112c5d9cd4675a11b150c4eac994a8c097b, thanks to @saladinkzn

**Comment by akhikhl** [comment]
@jmrossy , @shollander , the fix will be available in Gretty 1.4.0

**Comment by akhikhl** [comment]
Resolved with https://github.com/akhikhl/gretty/pull/276
The solution will be delivered with Gretty 1.4.0.
