### ISSUE TITLE
Gretty service port

### ISSUE THREAD

**Issue by globalbus** [akhikhl/gretty#239]
I have a problem with running Gretty 1.2.4 on FreeBSD based hosting. Because ignored servicePort and statusPort, application have a problem to run, mostly crashing on "Connection Refused" in ServicePort.groovy. Sometimes running, probably when it draw a free port. On previous version, 1.2.3 don't have such problems.

I have a limited access to TCP ports on machine, I must reserve them, before I can use them (because other user can reserve them too).

**Comment by akhikhl** [comment]
@saladinkzn provided the solution for this in Gretty 1.2.6. I am going to deliver Gretty 1.4.0, that will contain this solution as well.
