### ISSUE TITLE
How to specify httpIdleTimeout

### ISSUE THREAD

**Issue by mreddimasi** [akhikhl/gretty#241]
I'm trying to specify the httpIdleTimeout as below
gretty {

    contextPath = "/${archivesBaseName}"
    servletContainer = 'tomcat8'
    httpPort = 8080
    httpsEnabled = true
    httpsPort = 8444
    httpIdleTimeout = 60000
}

But the app wouldn't run with tomcatRun task, it throws an error at line no. 105 in TomcatServerConfigurer.groovy

The code snippet is 
httpConn.setProperty('keepAliveTimeout', params.httpIdleTimeout)

where httpConn is an instance of org.apache.catalina.connector.Connector, the setProperty expects arguments of String, but the second parameter is passed seems to be an Integer.

I also did try having the following jvmArgs, but doesn't seem to be working either.
jvmArgs = [-Dsun.net.client.defaultConnectTimeout=60000]

**Comment by akhikhl** [comment]
@saladinkzn released fix for this with Gretty 1.2.5. The fix will be available in "mainstream" Gretty 1.4.0 as well.
