### ISSUE TITLE
Support effort

### ISSUE THREAD

**Issue by saladinkzn** [akhikhl/gretty#248]
Hey all, I want to continue support of this plugin

You can use my [fork](https://github.com/saladinkzn/gretty) of plugin, feel free to post issues [here](https://github.com/saladinkzn/gretty/issues).

**Comment by djKianoosh** [comment]
What's your plan for publishing to maven central and/or renaming?

**Comment by saladinkzn** [comment]
I'm currently publishing it on jcenter as
'ru.shadam.gretty:gretty:${version}"

2016-04-02 20:45 GMT+03:00 Kianoosh Raika <notifications@github.com>:

**Comment by saladinkzn** [comment]
maven central is in plans
