### ISSUE TITLE
Create separate server configuration for running integration test cases 

### ISSUE THREAD

**Issue by manojiitkumar93** [akhikhl/gretty#250]
I am using gretty for my web application and configured variables respective to my application. i.e,
gretty {
    servletContainer = 'jetty9'
    jvmArgs '-Denv=dev','-Djava.library.path=lib-local/native'
    systemProperty "KEY1", "value1"
}

Now i want to run my integration tests with different configurations say...

gretty {
    servletContainer = 'jetty9'
    jvmArgs '-Denv=test,'-Djava.library.path=lib-local/native/test'
    integrationTestTask = "integrationTest"
    systemProperty "KEY2", "value2"
}

How can I achieve this.  
Would be grateful if greety supports different configuration for specific to integration tests..

**Comment by mohamnag** [comment]
I think you have to learn a bit about gradle basics. this can be easily done and has nothing to do with gretty.

**Comment by akhikhl** [comment]
Please consider using Gretty Farms for this:
http://akhikhl.github.io/gretty-doc/index.html
Farm configuration syntax is identical to Gretty configuration syntax.
