### ISSUE TITLE
Cannot add task ':run' as a task with that name already exists.

### ISSUE THREAD

**Issue by st9x3st9** [akhikhl/gretty#251]
How do I avoid this error? It seems that 2 seperate gradle files contain tasks that have `run` in them. But I am not explicitly calling on that task but I am getting the error.

**Comment by saladinkzn** [comment]
Actually, gretty checks if there's already task named `run` in your project. But maybe another plugin adding `run` task (e.g. application plugin) doesn't check that.

So the solution is to apply gretty last.

**Comment by st9x3st9** [comment]
That worked 👍
