### ISSUE TITLE
Gretty server is not starting as background process

### ISSUE THREAD

**Issue by st9x3st9** [akhikhl/gretty#252]
I am using the gretty plugin to test my code within gradle. Currently I have the following configuration for my gretty instance
```
gretty {
    httpPort = 23004
    servletContainer = "jetty7"
    consoleLogEnabled = false
    fileLogEnabled = true
    logFileName = "testing"
    logDir = "."
}
```
Then I am running this server with
```
./gradlew build appStart functionalTest --stacktrace
```
From what I read from the documentation the `appStart` method will make the process run in the background. The problem is that the gretty server just hangs with logs being written to console, and the `functionalTest` method is never reached.

I know with jettyEclipse you could just define `jettyEclipseRun.daemon = true` to make the process run in the background. Why is `appStart` not doing this?

**Comment by mkornipati** [comment]
@st9x3st9 Are you looking for the[ integration test ](http://akhikhl.github.io/gretty-doc/Integration-tests-support.html)feature?

**Comment by st9x3st9** [comment]
No I wrote my own functionalTesting library that will parse the log files generated by the jetty container.

**Comment by saladinkzn** [comment]
Well, appStart is waiting for container to stop, so integration test is really what you're looking for:

try:
```
gretty {
    integrationTestTask = 'functionalTest'
}
```
and then launch your task with 
```
./gradlew functionalTest --stacktrace
```

**Comment by danyorr** [comment]
Can I set integrationTestTask to run a task on a second module? For example:
`gretty {
    integrationTestTask = ':test:functionalTest'
}`

**Comment by akhikhl** [comment]
You can launch "external" webapp in the integration test by using Gretty Farms mechanism:
https://github.com/akhikhl/gretty/blob/master/examples/testWar/build.gradle#L49
