### ISSUE TITLE
Debugger failed to attach: handshake failed - received >POST /wlcApp/l< - expected >JDWP-Handshake<

### ISSUE THREAD

**Issue by zhangjie1980** [akhikhl/gretty#257]
hi,
  I encountered the above problem, may I ask how to solve, thank you。

**Comment by saladinkzn** [comment]
Hello
It looks like you're trying to access your web application from the port where debugger listens for incoming connection. Double check your port configuration (default port for webapp is 8080 and for debugger is 5005).

**Comment by akhikhl** [comment]
I consider the problem solved and close the issue. Please reopen, if needed.

**Comment by rama213** [comment]
How to put the debugger port no and where to put it for debugging quarkus application
