### ISSUE TITLE
Changing product name

### ISSUE THREAD

**Issue by h3adache** [akhikhl/gretty#262]
The documentation for buildProduct (http://akhikhl.github.io/gretty-doc/Product-generation.html)
Specifies that the product will be built to build/output/${project.name}.

The archive file when running archiveProduct creates a $project.name-$version zip.
It would be nice to be able to name the product that way as well.

The use case is that I currently download the latest zip and ln the product directory after unzipping it.
It would be nice if that directory was versioned as well so that it doesn't overwrite previous installs (for easier versioning/rolling back

**Comment by saladinkzn** [comment]
This feature is available in my fork by adding includeVersion property:
product {
     includeVersion = true
}

**Comment by akhikhl** [comment]
@saladinkzn provided the solution for this in Gretty 1.2.6. I am going to deliver Gretty 1.4.0, that will contain this solution as well.
