### ISSUE TITLE
gretty failing to start on Gradle 2.14

### ISSUE THREAD

**Issue by cais-erik** [akhikhl/gretty#265]
It seems the impl of the Jacoco plugin has changed a bit with the recent Gradle update.  After updating to Gradle 2.14, when I attempt to execute the tomcatRun task an error is thrown regarding the applyTo() method of a Jacoco plugin-supplied class.  And I can't seem to find a way to avoid the issue even though I don't care to utilize the Jacoco functionality.  

It's been awhile since this project has been updated.  Please let me know if you anticipate having the time/inclination to resolve this relatively soon.  Thanks.

**Comment by saladinkzn** [comment]
You can use my fork of gretty where I've fixed this issue: https://github.com/saladinkzn/gretty. Feel free to submit issues there if you find any.

**Comment by devng** [comment]
I have the same error, with Gradle 2.14.1 i get the following error

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':webapp:jettyRun'.
> Could not find method applyTo() for arguments [org.akhikhl.gretty.JacocoHelper@2ea8ec4a] on object of type org.gradle.testing.jacoco.plugins.JacocoPluginExtension.
```

With Gradle 2.13 everything works just fine, so it must be something that was introduced in Gradle 2.14

**Comment by cais-erik** [comment]
The fork @saladinkzn pointed me to worked correctly.  I believe it is more recently updated than this one.

**Comment by akhikhl** [comment]
Resolved with https://github.com/akhikhl/gretty/pull/276.
The solution will be delivered with Gretty 1.4.0.
