### ISSUE TITLE
Cannot change strategy of configuration ':apt' after it has been resolved

### ISSUE THREAD

**Issue by yissachar** [akhikhl/gretty#284]
When using the Gretty plugin in combination with the [APT plugin](https://github.com/tbroyer/gradle-apt-plugin), I receive the following error:

> Cannot change strategy of configuration ':apt' after it has been resolved

in Gradle < 3.0 this was just a warning and I was able to proceed anyway, but in Gradle 3.0 this is an error that prevents me from building the project.

I am using Gretty 1.4.0 and Gradle-APT-Plugin 0.8 (both latest versions). Simple build.gradle that you can use to reproduce this:

```
apply plugin: 'java'
apply plugin: 'net.ltgt.apt'
apply plugin: 'org.akhikhl.gretty'

buildscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath "net.ltgt.gradle:gradle-apt-plugin:0.8"
        classpath 'org.akhikhl.gretty:gretty:1.4.0'
    }
}
```

**Comment by tbroyer** [comment]
You can count it as a gradle-apt-plugin bug, which should now be fixed (not yet released though)
