### ISSUE TITLE
Can we fix the scrambled table in Gretty-configuration.html?

### ISSUE THREAD

**Issue by duhang** [akhikhl/gretty#307]
http://akhikhl.github.io/gretty-doc/Gretty-configuration.html

the 2nd-half of the table is scrambled

| Property | Type | Default | Purpose

| contextPath | String | "/${project.name}" | Context path for the web-app.
contextPath affects only gretty tasks. If you assemble WAR file and deploy it to some servlet container, you must define context path by means of that container.

**Comment by JLLeitschuh** [comment]
Looks like there is a PR to fix this:
https://github.com/akhikhl/gretty-doc/pull/5

**Comment by akhikhl** [comment]
Fixed, please have a look
http://akhikhl.github.io/gretty-doc/Gretty-configuration.html

**Comment by JLLeitschuh** [comment]
Looking good!!!
