### ISSUE TITLE
Documentation configs page broken layout

### ISSUE THREAD

**Issue by Hubbitus** [akhikhl/gretty#317]
http://akhikhl.github.io/gretty-doc/Gretty-configuration.html:
Tail of table looks broken:
![image](https://cloud.githubusercontent.com/assets/720349/21540599/51b27ac8-cdc1-11e6-9d17-b9fef9d193ac.png)

**Comment by akhikhl** [comment]
@Hubbitus , issue resolved:
http://akhikhl.github.io/gretty-doc/Gretty-configuration.html

**Comment by Hubbitus** [comment]
Thank you.
