### ISSUE TITLE
Missing Annotations

### ISSUE THREAD

**Issue by mandrachek** [akhikhl/gretty#318]
I have gretty 1.4.0 configured, using jetty9.

Eclipse is able to find the @WebServlet annotation dependency, but cannot find @WebServletContextListener or @ServletFilter, which are part of servlet api 3.+

**Comment by akhikhl** [comment]
Does your project compile without errors? Is it the problem with IDE lookup/decoration?

**Comment by mandrachek** [comment]
Sorry, gave up on this approach and switched to using Dropwizard.
