### ISSUE TITLE
Could not find jai_core.jar

### ISSUE THREAD

**Issue by zhaiqianfeng** [akhikhl/gretty#322]
when I follow up http://akhikhl.github.io/gretty-doc/Getting-started.html,I got a error:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not resolve all files for configuration ':compileClasspath'.
> > Could not find jai_core.jar (javax.media:jai_core:1.1.3).
>   Searched in the following locations:
>       https://jcenter.bintray.com/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar

please help me,thanks.

**Comment by akhikhl** [comment]
Hi @zhaiqianfeng ,
The issue is caused by invalid publication of jai_core at jcenter and maven-central.
In order to resolve the issue, please add the following to your gradle script:

```groovy
repositories {
  maven { url 'http://download.osgeo.org/webdav/geotools/' }
  jcenter()
}
```

Please note that inclusion order is important here, geotools must come before jcenter.
Please let me know if it fixes the issue.

**Comment by zhaiqianfeng** [comment]
Thank you very much.

**Comment by at7000ft** [comment]
Thank you, saved me at least half a day.

**Comment by Vampire** [comment]
Just my 2ct, the publication is not "invalid", the license just doesn't allow its upload to Maven Central.
So from the guide for Maven Central:
![grafik](https://user-images.githubusercontent.com/325196/55793812-070ea180-5ac4-11e9-8d80-cae80b84fa6f.png)
was followed:
![grafik](https://user-images.githubusercontent.com/325196/55793853-27d6f700-5ac4-11e9-9f59-30b30e586c55.png)
Besides that the manual download site does no longer exist.

**Comment by chris1248** [comment]
Saved me half a day too. Thank you very much!

**Comment by charlesritchea** [comment]
http://download.osgeo.org/webdav/geotools/ is 404 now

**Comment by grimsa** [comment]
In case anyone encounters a similar issue, the osgeo repo URL is now `https://repo.osgeo.org/repository/release/`

**Comment by zjiawei3** [comment]
The solution above will prioritize pulling artifact from this osgeo repo instead mavenCentral. If you see the following error after the log4j 0day:
Could not find log4j-1.2.17.jar (log4j:log4j:1.2.17).
     Searched in the following locations:
         https://repo.osgeo.org/repository/release/log4j/log4j/1.2.17/log4j-1.2.17.jar

Try the following build instead

    mavenCentral {
        content {
            excludeModule("javax.media", "jai_core")
        }
    }
    maven { url 'https://repo.osgeo.org/repository/release/' }
