### ISSUE TITLE
Update the Gretty version in the Gradle plugin portal?

### ISSUE THREAD

**Issue by boris-petrov** [akhikhl/gretty#325]
I'm not sure whether you are going to update the version of Gretty here:

https://plugins.gradle.org/plugin/org.akhikhl.gretty

I don't see it mentioned in the "Getting started" page and am not sure whether I should continue using the "new" style of Gradle plugins:

```groovy
plugins {
	id 'org.akhikhl.gretty' version '1.4.0'
}

apply plugin: 'org.akhikhl.gretty'
```

**Comment by akhikhl** [comment]
Yes, I will update it in the plugin portal as well, over this weekend.

**Comment by jonatanloya** [comment]
Hi Guys,

Please update to 1.4.1 gradle plugins. 

Thanks
