### ISSUE TITLE
jetty 9 uses thrice more time to start then jetty 8

### ISSUE THREAD

**Issue by TomDmitriev** [akhikhl/gretty#35]
I do not know if it has to do anything with gretty plugin or jetty itself. When I run jetty 9 as a standalone server it starts almost instantly and deploys my app in about 10 seconds but when I run `gradle appRun` I have to wait at the step `INFO  - jetty-9.2.1.v20140609` for about 50 seconds. If I change to `servletContainer = 'jetty8'` the step only takes about 15 seconds. When I turn on debugging I can see endless messages like `[DEBUG] [org.eclipse.jetty.util.Scanner] scan accepted  /home/artyom/IdeaProjects/prj1/src/main/webapp/WEB-INF/...` with different paths, so I think it is connected with scanning jetty performs. By any chance do you know why there is such a big difference between jetty 8 and jetty 9 and what I can be done about it?

**Comment by xhkz** [comment]
@TomDmitriev Hi Artyom, may I know what kind of hardware issue is causing this problem? I am currently having same endless log like '[org.eclipse.jetty.util.Scanner] scanned [dir, dir, ..........]' when using appRun. Thanks.
