### ISSUE TITLE
Running integration tests with war file?

### ISSUE THREAD

**Issue by jl4282** [akhikhl/gretty#350]
Is it possible to run integration tests with jettyStartWar? It looks like appBeforeIntegrationTest does not use a war file according to the documentation. What is the method of running integration tests using a war file?

**Comment by cloutierjo** [comment]
After struggling with this issue for a few day, I found a workarround by overridden the tasks:

`// run integration test with the war compiled server
import org.akhikhl.gretty.*
task('AppWarBeforeIntegrationTest', type: AppBeforeIntegrationTestTask) {
    inplace = false
    integrationTestTask 'ItTest'
}
task('AppWarAfterIntegrationTest', type: AppAfterIntegrationTestTask) {
    integrationTestTask 'ItTest'
}`

It would still be great to be able to simply configure that without overriding

**Comment by jl4282** [comment]
I found these examples [here](http://akhikhl.github.io/gretty-doc/Override-context-path-in-integration-test-tasks.html) and [here](https://github.com/akhikhl/gretty/blob/fdc7aad35322b9786406e93715e57bde540a8551/examples/testWar/build.gradle). They show how to use a farm to prepare the war file first.
