### ISSUE TITLE
Can't stop farm after error appears in farmBeforeIntegrationTest

### ISSUE THREAD

**Issue by triffer** [akhikhl/gretty#351]
I have a integration test that will start four webapps for testing. If an error (e.g. "java.lang.Exception: Failed to start component [StandardServer[-1]]") occurs during farmBeforeIntegrationTest the server won't be shutdown. 
When I run farmAfterIntegrationTest explicitly after the before failed, this task will also fail with the following message: Gretty seems to be not running, cannot send command 'stop' to it.
I also tried running farmStop, but I got the same message.

**Comment by echatman** [comment]
I'm running into a similar problem - do you remember what the solution was?

**Comment by triffer** [comment]
There was no real solution, just a workaround. We had a shell script in our pipeline that stopped those processes when an error occured. Meanwhile we are using Docker.
