### ISSUE TITLE
Debugger doesn't work on IntelliJ

### ISSUE THREAD

**Issue by mrichardsonjr** [akhikhl/gretty#36]
I read the documentation here (http://akhikhl.github.io/gretty-doc/Debugger-support.html) about using the debugger.  I'm using IntelliJ IDEA, but I can't get the debugger to work.  I've tried using the debugger from both the command line and the gradle plugin, and I've tried both the jettyStartDebug and jettyRunDebug tasks.  I also tried using the jettyStart task with the IntelliJ debug icon, but that didn't work either.

**Comment by MrYang** [comment]
thanks very mush

**Comment by mohamnag** [comment]
I had the same problem with debugging and even though I could make the debugging work but I have to say this is really the strangest setup I have seen using intellij debugging a local process.

even the official outdated gradle jetty plugin can be started easily in debug mode and inetllij picks up the debug connection. I'm not a gradle plugin profi but I'm using intellij for a good 2 years now and this is not really easy and preferred way of debugging in intellij.

could you please keep this issue open until solution gets as easy as original gradle jetty plugin?

**Comment by saladinkzn** [comment]
it can't be easy cuz currently gretty has two running java apps: main
(containgin gradle plugin, scanner etc) and Runner app that contains only
application server an you web application.

2016-04-21 22:21 GMT+03:00 Mohammad Naghavi <notifications@github.com>:

**Comment by saladinkzn** [comment]
The only way to debug is have a remote debugging

2016-04-21 22:51 GMT+03:00 Тимур Шакуров <saladinkzn@gmail.com>:

**Comment by mohamnag** [comment]
mmm ... thats actually interesting because integration test tasks work with IDEA's debugging seamlessly. maybe they have other structure.

**Comment by mohamnag** [comment]
I have to take my last comment back, the integration tests work only if you want to debug the test itself. debugging the code on server side is impossible.

**Comment by johnnywiller** [comment]
Configuring a Remote worked for me.
I'm using IntelliJ IDEA 2018.3.5
Just RUN #appRunDebug in RUN mode, followed by a Remote in DEBUG mode
2 running configs will be running at the same time
