### ISSUE TITLE
Fork project due to unreachable maintainer

### ISSUE THREAD

**Issue by henrik242** [akhikhl/gretty#423]
@akhikhl hasn't been available since June 2017.  A fork has been established at: https://github.com/gretty-gradle-plugin/gretty

**Comment by woldie** [comment]
@javabrett @henrik242 @akhikhl so super that the great fork of 2018 is underway!  I still think we should pick a new name too just so there is no confusion for users or with regards to trademark ownership.  Is there any appetite for that?

If no, then once we're published to a maven repo, we could lobby the gradle org to update the maven coords for gretty plugin to our artifact and get the gradle docs updated. I could take that task in any case.

**Comment by henrik242** [comment]
I think we should just keep the gretty name. But let's take this discussion in https://github.com/gretty-gradle-plugin/gretty

**Comment by javabrett** [comment]
@henrik242 I think this can be closed now.

**Comment by henrik242** [comment]
Fixed by 2.1.0 release: https://github.com/gretty-gradle-plugin/gretty/issues/8

**Comment by sergiomichels** [comment]
I think this repo should mention the fork at readme since it's not visible that an alternative exists :)

**Comment by javabrett** [comment]
> I think this repo should mention the fork at readme since it's not visible that an alternative exists :)

Best option is to send a Pull Request for this and see if it is merged.  Note that Gradle doc link has been changed but not yet released: https://github.com/gradle/gradle/commit/db8dc9b1e357c4c26eba198125e5b234c5653cdd .
