### ISSUE TITLE
how to appStartWar with war generated in subproject?

### ISSUE THREAD

**Issue by damnms** [akhikhl/gretty#444]
i added the gretty app to one of my subprojects where the .war is generated.
when i execute the task appRunWar, i see that tomcat is starting but i see no deployment of any war file or whatsoever. the url that is produced (http://localhost:8080/ecaas_tarif-browser-web-core) produces a 404. Is there any way to see what is going on behind the scenes? as the url is wrong (or nothing is deployed), i guess there are some errors which are somehow hidden.

> 16:14:12: Executing task 'appRunWar'...
> 
> 
> > Configure project :team_tarif-browser-web-core
> Inferred project: team_tarifbrowser, version: 3.1.0-dev.5.uncommitted+ECPC.3744.war.deployment.dc83a11
> 
> > Configure project :
> Property named 'artifactrepoUsername' not set.
> Property named 'artifactrepoPassword' not set.
> 
> > Task :team_tarif-browser-common:schemaGen_ch-forum_datenaustausch-invoice400 UP-TO-DATE
> > Task :team_tarif-browser-common:schemaGen_ch-forum_datenaustausch-invoice410 UP-TO-DATE
> > Task :team_tarif-browser-common:schemaGen_com-adcubum-xsd-eclaim-common UP-TO-DATE
> > Task :team_tarif-browser-common:schemaGen_com-adcubum-xsd-eclaim-invoice UP-TO-DATE
> > Task :team_tarif-browser-common:schemaGen_syriusRuleDef.xsd UP-TO-DATE
> > Task :team_tarif-browser-common:compileJava UP-TO-DATE
> > Task :team_tarif-browser-common:processResources UP-TO-DATE
> > Task :team_tarif-browser-common:classes UP-TO-DATE
> > Task :team_tarif-browser-common:jar UP-TO-DATE
> > Task :team_tarif-browser-core-common:compileJava UP-TO-DATE
> > Task :team_tarif-browser-core-common:processResources NO-SOURCE
> > Task :team_tarif-browser-core-common:classes UP-TO-DATE
> > Task :team_tarif-browser-core-common:jar UP-TO-DATE
> 
> > Task :team_tarif-browser-core-domain:compileJava
> 
> > Task :team_tarif-browser-core-domain:processResources UP-TO-DATE
> > Task :team_tarif-browser-core-domain:classes
> > Task :team_tarif-browser-core-domain:jar UP-TO-DATE
> Note: Hibernate JPA 2 Static-Metamodel Generator 5.4.9.Final
> Note: C:\Users\gnah\IdeaProjects\tarifbrowser\core-domain\src\main\java\com\adcubum\mediframe\browser\core\repositories\DefaultRepositoryFactory.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> > Task :team_tarif-browser-core:compileJava UP-TO-DATE
> > Task :team_tarif-browser-core:processResources UP-TO-DATE
> > Task :team_tarif-browser-core:classes UP-TO-DATE
> > Task :team_tarif-browser-core:jar UP-TO-DATE
> > Task :team_tarif-browser-web-common:compileJava UP-TO-DATE
> > Task :team_tarif-browser-web-common:processResources NO-SOURCE
> > Task :team_tarif-browser-web-common:classes UP-TO-DATE
> > Task :team_tarif-browser-web-common:jar UP-TO-DATE
> > Task :team_tarif-browser-web-core:compileJava UP-TO-DATE
> > Task :team_tarif-browser-web-core:processResources UP-TO-DATE
> > Task :team_tarif-browser-web-core:classes UP-TO-DATE
> > Task :team_tarif-browser-web-core:war UP-TO-DATE
> > Task :team_tarif-browser-web-core:prepareArchiveWebApp UP-TO-DATE
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/C:/Users/gnah/.gradle/caches/modules-2/files-2.1/org.codehaus.groovy/groovy/2.5.8/2f1e8ea55e625fe51e85ef35eb067f1d9c61772d/groovy-2.5.8.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
> WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> Dez. 10, 2019 4:14:17 NACHM. org.apache.coyote.AbstractProtocol init
> INFORMATION: Initializing ProtocolHandler ["http-nio-8080"]
> Dez. 10, 2019 4:14:25 NACHM. org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
> INFORMATION: Using a shared selector for servlet write/read
> Dez. 10, 2019 4:14:25 NACHM. org.apache.catalina.core.StandardService startInternal
> INFORMATION: Starting service [Tomcat]
> Dez. 10, 2019 4:14:25 NACHM. org.apache.catalina.core.StandardEngine startInternal
> INFORMATION: Starting Servlet Engine: Apache Tomcat/9.0.13
> Dez. 10, 2019 4:14:25 NACHM. org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
> INFORMATION: No global web.xml found
> Dez. 10, 2019 4:14:27 NACHM. org.apache.jasper.servlet.TldScanner scanJars
> INFORMATION: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
> Dez. 10, 2019 4:14:27 NACHM. org.apache.catalina.core.ApplicationContext log
> INFORMATION: No Spring WebApplicationInitializer types detected on classpath
> Dez. 10, 2019 4:14:30 NACHM. org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
> WARNUNG: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [2,947] milliseconds.
> Dez. 10, 2019 4:14:30 NACHM. org.apache.coyote.AbstractProtocol start
> INFORMATION: Starting ProtocolHandler ["http-nio-8080"]
> 16:14:30 INFO  Tomcat 9.0.13 started and listening on port 8080
> 16:14:30 INFO  team_tarif-browser-web-core runs at:
> 16:14:30 INFO    http://localhost:8080/team_tarif-browser-web-core
> 
> > Task :team_tarif-browser-web-core:appRunWar
> Press any key to stop the server.

**Comment by javabrett** [comment]
Do you have a servlet mapped to path “” or “/“ or have a default servlet or welcome file?

**Comment by damnms** [comment]
this was an error on my side.
the .war file which was generated did not contain all files, so no .html was shown.
unfortunately, i forgot to close that issue
