### ISSUE TITLE
How to add additional classes to webapp classpath

### ISSUE THREAD

**Issue by rainoko** [akhikhl/gretty#98]
Because jacoco not suitable for me, I have to use cobertura for code coverage. This means I need add instrumented classes to webapp classpath for gretty before running integration test.
I cant it figured out how to do this.

in jetty plugin it is possible to do something like
integrationTest.doFirst {
  println 'Start Jetty'
  tasks.jettyRun.daemon=true
  ....
  tasks.jettyRun.classpath= files("${project.buildDir}/instrumented_classes")+ sourceSets.main.runtimeClasspath
  ....
  tasks.jettyRun.execute()
}

**Comment by levsa** [comment]
Hi, 

Can this be used with "sourceSets.integrationTest.runtimeClasspath" for instance (which is a fileset), or it converted into path (colon separated directories)?

**Comment by levsa** [comment]
Has this changed in 1.2.3? Now I get "no protocol" error for classPath entry that worked previously.

**Comment by akhikhl** [comment]
I'll try to reproduce it

**Comment by akhikhl** [comment]
Same was reported here: https://github.com/akhikhl/gretty/issues/178#issuecomment-105422643

**Comment by ralphvanetten** [comment]
Could you please explain how you got cobertura working?

Because just adding 

    afterEvaluate {
        tasks.appBeforeIntegrationTest {
            gretty { 
                  classPath "${project.buildDir}/instrumented_classes"
            }
        }
    }

does not seem to work as it adds the `instrumented_classes` to the end of the classpath. For cobertura to work the `instrumented_classes` need to be at the front of the classpath (or the default `build/classes/main` entry removed from the classpath)
